### ISSUE TITLE
HTML+CSS

### ISSUE THREAD

**Issue by klutz2121** [klutz2121/Basic--Programming#8]
Create a name list on the webpage.

**Comment by ghost** [comment]
There are three list types in HTML: unordered list — used to group a set of related items in no particular order. ordered list — used to group a set of related items in a specific order. description list — used to display name/value pairs such as terms and definitions.

```
unordered list:  <ul></ul>
ordered list:     <ol></ol>
item list:         <li>  </li>
```
Example:

Unorded list (Bullets)
```
<ul>                                                  
    <li></li>
    <li></li>
</ul>
```
<ul>                                                  
    <li>  Somewhat   </li>
    <li>  Somewhat   </li>
</ul>

ordered list    (Numbers)      
```
<ol>
    <li></li>
    <li></li>
</ol>
```
<ol>
    <li> Somewhat  </li>
    <li> Somewhat  </li>
</ol>
